name: Test Get Data

on: [workflow_dispatch]

jobs:
  getdata:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install -r requirements.txt
    - name: Setup access credentials
      env:
        GBQ_ACCESS_DATA: ${{ secrets.GBQ_ACCESS_DATA }}
      run: echo "$GBQ_ACCESS_DATA" > ./cred.json
    - name: Run job
      env:
        GOOGLE_APPLICATION_CREDENTIALS: ./cred.json
      run: python plugin_stats.py
